# Generated by Django 5.0.3 on 2024-04-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(max_length=50)),
                ('card_image', models.FileField(default=None, max_length=250, null=True, upload_to='card_image/')),
            ],
        ),
    ]
